# Generated by Django 5.2.4 on 2025-08-09 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerLogin',
            new_name='Login',
        ),
    ]
